services:
  php:
    build: .
    image: thomas-php
    working_dir: /var/task
    volumes:
      - .:/var/task
      - ./storage:/tmp/storage
    ports:
      - "89:80"

  composer:
    image: thomas-php
    working_dir: /var/task
    volumes:
      - .:/var/task
      - ./tmp:/tmp
    entrypoint: ["composer"]

  redis:
    image: redis
    ports:
      - "6382:6379"

  dynamo:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8009:8000"