name: Tests And Coverage

on:
  push:
    branches: [ main ]
jobs:
  thomas-api-tests-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Up
        run: docker-compose up -d
      - name: Replace Values in Config Files
        run: |
          cat .env.github-testing | sed s/{{LDB_KEY}}/${{ secrets.LDB_KEY }}/g | sed s/{{KB_USER}}/${{ secrets.KB_USER }}/g | sed s/{{KB_PASS}}/${{ secrets.KB_PASS }}/g | sed s/{{KBRTI_USER}}/${{ secrets.KBRTI_USER }}/g | sed s/{{KBRTI_PASS}}/${{ secrets.KBRTI_PASS }}/g | sed s/{{DARWIN_TOPIC_USER}}/${{ secrets.DARWIN_TOPIC_USER }}/g | sed s/{{DARWIN_TOPIC_PASS}}/${{ secrets.DARWIN_TOPIC_PASS }}/g > .env
      - name: Composer Install, DB Migrate and Seed
        run: |
          pwd
          chmod 777 -R /home/runner/work/thomas-api/thomas-api/
          composer install
          docker-compose exec -T php php artisan dynamo:setup add --confirm
      - name: Run All Tests
        run: |
          docker-compose exec -T php ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: phpunit-coverage-badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          report: coverage.xml
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
